#  MACHINE LEARNING

#  Scaling And Encoding

In [2]:
import pandas as pd

df = pd.DataFrame(
{'Age': [23, 20, 30],
'experience':[ 3, 1, 7],
'salary':[3000, 3500, 5000]}
)

df

   Age  experience  salary
0   23           3    3000
1   20           1    3500
2   30           7    5000

In [6]:
from sklearn.preprocessing import MinMaxScaler


min_max_scaler = MinMaxScaler()
min_max_scaler.fit(df[['Age', 'experience', 'salary']])

df[['AgeScaled', 'experience_scaled', 'salary_scaled']] = min_max_scaler.transform(df[['Age', 'experience', 'salary']])
df

   Age  experience  salary  AgeScaled  experience_scaled  salary_scaled
0   23           3    3000        0.3           0.333333           0.00
1   20           1    3500        0.0           0.000000           0.25
2   30           7    5000        1.0           1.000000           1.00

In [7]:
from sklearn.preprocessing import StandardScaler


standard_scaler = StandardScaler()
standard_scaler.fit(df[['Age', 'experience', 'salary']])

df[['AgeScaled', 'experience_scaled', 'salary_scaled']] = standard_scaler.transform(df[['Age', 'experience', 'salary']])
df

   Age  experience  salary  AgeScaled  experience_scaled  salary_scaled
0   23           3    3000  -0.318223          -0.267261      -0.980581
1   20           1    3500  -1.034224          -1.069045      -0.392232
2   30           7    5000   1.352447           1.336306       1.372813

In [8]:
from sklearn.preprocessing import RobustScaler


robust_scaler = RobustScaler()
robust_scaler.fit(df[['Age', 'experience', 'salary']])

df[['AgeScaled', 'experience_scaled', 'salary_scaled']] = robust_scaler.transform(df[['Age', 'experience', 'salary']])
df

   Age  experience  salary  AgeScaled  experience_scaled  salary_scaled
0   23           3    3000        0.0           0.000000           -0.5
1   20           1    3500       -0.6          -0.666667            0.0
2   30           7    5000        1.4           1.333333            1.5

In [9]:
from sklearn.preprocessing import MaxAbsScaler


MaxAbs_scaler = MaxAbsScaler()
MaxAbs_scaler.fit(df[['Age', 'experience', 'salary']])

df[['AgeScaled', 'experience_scaled', 'salary_scaled']] = MaxAbs_scaler.transform(df[['Age', 'experience', 'salary']])
df

   Age  experience  salary  AgeScaled  experience_scaled  salary_scaled
0   23           3    3000   0.766667           0.428571            0.6
1   20           1    3500   0.666667           0.142857            0.7
2   30           7    5000   1.000000           1.000000            1.0

In [10]:
df = pd.DataFrame({
    'size':['small', 'large', 'medium', 'medium', 'small'],
'brand':['addidas', 'nike', 'nike', 'addidas', 'addidas'], 
'warranty': [ 1, 2, 2, 1.5, 1],
'color': ['red', 'blue', 'red', 'blue', 'green'],
'price': [100, 150, 200, 250, 300]
})

df

     size    brand  warranty  color  price
0   small  addidas       1.0    red    100
1   large     nike       2.0   blue    150
2  medium     nike       2.0    red    200
3  medium  addidas       1.5   blue    250
4   small  addidas       1.0  green    300

In [13]:
from sklearn.preprocessing import OrdinalEncoder


size_order = ['small', 'medium', 'large']

ordinal_encoder = OrdinalEncoder(categories=[size_order])

ordinal_encoder.fit(df[['size']])

df['size_transformed'] = ordinal_encoder.transform(df[['size']])
df['size_transformed'] = df['size_transformed'].astype(int)

df

     size    brand  warranty  color  price  size_transformed
0   small  addidas       1.0    red    100                 0
1   large     nike       2.0   blue    150                 2
2  medium     nike       2.0    red    200                 1
3  medium  addidas       1.5   blue    250                 1
4   small  addidas       1.0  green    300                 0